[versions]
agp = "8.3.1"
androidxJunit = "1.1.3"
appcompatVersion = "1.4.0"
compiler = "4.15.1"
constraintlayoutVersion = "2.1.2"
converterGson = "2.9.0"
coreKtxVersion = "1.7.0"
espressoCoreVersion = "3.4.0"
firebaseAuth = "22.3.1"
firebaseBom = "32.8.1"
fragment = "1.3.0"
fragmentKtx = "1.6.0"
glide = "4.16.0"
googleMaterial = "1.9.0"
guava = "31.1-android"
kotlin = "1.9.0"
coreKtx = "1.13.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
legacySupportV4 = "1.0.0"
lifecycleRuntimeKtx = "2.6.2"
loggingInterceptor = "4.11.0"
material = "1.11.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
materialVersion = "1.4.0"
navigationFragmentKtxVersion = "2.7.4"
navigationUiKtxVersion = "2.7.4"
picasso = "2.71828"
playServicesAuth = "21.1.0"
retrofit = "2.9.0"
roomRuntime = "2.6.1"
shimmer = "0.5.0"
tensorflowLite = "2.13.0"
tensorflowLiteMetadata = "0.4.4"
tensorflowLiteSupport = "0.4.4"
tensorflowLiteTaskVision = "0.4.4"
viewpager2 = "1.1.0"
firebaseStorageKtx = "21.0.0"
navigationFragmentKtx = "2.7.7"
navigationUiKtx = "2.7.7"
firebaseFirestoreKtx = "25.0.0"
googleServices = "4.4.2"
firebaseFirestore = "25.0.0"
cameraxVersion = "1.3.0"
viewpager2Version = "1.0.0"
kotlinParcelize = "1.8.10"
runtimeAndroid = "1.6.7"
preferenceKtx = "1.2.1"

[libraries]
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraxVersion" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraxVersion" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraxVersion" }
androidx-constraintlayout-v212 = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayoutVersion" }
androidx-appcompat-v140 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-ktx-v170 = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
androidx-espresso-core-v340 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
androidx-fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-junit-v113 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
androidx-legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupportV4" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-navigation-ui-ktx-v274 = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationUiKtxVersion" }
androidx-navigation-fragment-ktx-v274 = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtxVersion" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
androidx-viewpager2-v100 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2Version" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebaseAuth" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
firebase-storage-ktx = { group = "com.google.firebase", name = "firebase-storage-ktx", version.ref = "firebaseStorageKtx" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx", version.ref = "firebaseFirestoreKtx" }
google-services = { group = "com.google.gms", name = "google-services", version.ref = "googleServices" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }
material-v140 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
material-v190 = { module = "com.google.android.material:material", version.ref = "googleMaterial" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit2-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
tensorflow-lite-support = { module = "org.tensorflow:tensorflow-lite-support", version.ref = "tensorflowLiteSupport" }
tensorflow-lite = { module = "org.tensorflow:tensorflow-lite", version.ref = "tensorflowLite" }
tensorflow-tensorflow-lite-metadata = { module = "org.tensorflow:tensorflow-lite-metadata", version.ref = "tensorflowLiteMetadata" }
tensorflow-tensorflow-lite-task-vision = { module = "org.tensorflow:tensorflow-lite-task-vision", version.ref = "tensorflowLiteTaskVision" }
androidx-runtime-android = { group = "androidx.compose.runtime", name = "runtime-android", version.ref = "runtimeAndroid" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preferenceKtx" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlinParcelize" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
